stark überarbeitet
git-svn-id: https://callmonitor.svn.sourceforge.net/svnroot/callmonitor/fritzbox/callmonitor/trunk@105 e872857c-5b07-0410-aa81-e3586f851bf3

diff --git a/base/usr/bin/mail b/base/usr/bin/mail
--- a/base/usr/bin/mail
+++ b/base/usr/bin/mail
@@ -7,7 +7,7 @@ readonly TMP="/tmp/$PROGRAM"
 usage() {
 	cat <<EOF
 Usage: $PROGRAM {send|sendonce|enqueue} [MAILER_OPTION]...
-       $PROGRAM {process|config}
+       $PROGRAM {process|config|list}
 EOF
 	echo
 	"$MAILER" -?
@@ -17,15 +17,159 @@ if [ ! -e "$SPOOL" ]; then
 	mkdir -p "$SPOOL"
 fi
 
+# apply a function to each item in a comma-separated list
+foreach() {
+	local - list="$1" IFS=,
+	alias func="$2"
+	set -f
+	for item in $1; do
+		eval 'func "$item"'
+	done
+	unalias func
+}
+
+# add an item to a comma-separated list
+add() {
+	local name="$1" item="$2"
+	eval "$name=\"\$$name\${$name:+,}\$item\""
+}
+
+escape() {
+	echo "$1" | sed -e "s/'/'\\\\''/g;1s/^/'/;\$s/$/'/"
+}
+
+process_mail() {
+	local id="$1"
+	trap "spool $id" EXIT
+	local dir="$TMP/$id"
+	local tmparchive="$dir.tar.gz"
+	unspool $id || return 1
+	if send $id; then
+		remove $id
+	else
+		spool $id
+	fi
+	trap "" EXIT
+}
+
+# try to send a mail that has been prepared
+send() (
+	local id="$1"
+	local dir="$TMP/$id"
+	cd "$dir"
+	./send
+	return $?
+)
+
+# remove a mail that should not be send again (it does not matter what state
+# the mail is in)
+remove() {
+	local id="$1"
+	local dir="$TMP/$id"
+	local archive="$SPOOL/$id.tar.gz"
+	local tmparchive="$dir.tar.gz"
+	rm -f "$archive" "$tmparchive"
+	rm -rf "$dir"
+}
+
+# move mail to spool directory for later processing (and clean up)
+spool() {
+	local id="$1"
+	local dir="$TMP/$id"
+	local tmparchive="$TMP/$id.tar.gz"
+	if [ ! -e "$tmparchive" ]; then
+		pack $id
+	fi
+	ln "$tmparchive" "$SPOOL"/ && rm "$tmparchive"
+	if [ -d "$dir" ]; then
+		rm -rf "$dir"
+	fi
+}
+unspool() {
+	local id="$1"
+	local archive="$SPOOL/$id.tar.gz"
+	ln "$archive" "$TMP"/ && rm "$archive"
+	unpack $id
+}
+
+prepare_mail() {
+	local id="$1" TEMP
+	local dir="$TMP/$id"
+	mkdir -p "$dir"
+	COUNT=0
+	save_attachment() {
+		local file="$1" realpath
+		local basename="$(basename "$file")"
+		if [ "$file" = "-" ]; then
+			basename="stdin.txt"
+			realpath="-"
+		else
+			realpath="$(realpath "$file")"
+		fi
+		local subdir="$COUNT"
+		local target="$dir/$subdir/$basename"
+		mkdir "$dir/$subdir"
+		case "$realpath" in
+			/var/*|-) cat "$file" > "$target" ;;
+			*)	ln -s "$realpath" "$target" ;;
+		esac
+		add TEMP "$subdir/$basename"
+		let COUNT="$COUNT + 1"
+	}
+	if [ "${ATTACHMENTS+set}" ]; then
+		unset TEMP
+		foreach "$ATTACHMENTS" save_attachment
+		ATTACHMENTS="$TEMP"
+	fi
+	if [ "${INLINES+set}" ]; then
+		unset TEMP
+		foreach "$INLINES" save_attachment
+		INLINES="$TEMP"
+	fi
+	set -- "$MAILER" \
+		${SUBJECT+	   "-s" "$SUBJECT"} \
+		${FROM+		   "-f" "$FROM"} \
+		${TO+		   "-t" "$TO"} \
+		${MAILSERVER+  "-m" "$MAILSERVER"} \
+		${AUTHNAME+    "-a" "$AUTHNAME"} \
+		${PASSWORD+    "-w" "$PASSWORD"} \
+		${ATTACHMENTS+ "-d" "$ATTACHMENTS"} \
+		${INLINES+	   "-i" "$INLINES"}
+	script="$dir/send"
+	{
+		printf "#!/bin/sh\n"
+		for arg in "$@"; do
+			printf "%s " "$(escape "$arg")"
+		done
+		printf "\n"
+	} > "$script"
+	chmod +x "$script"
+	echo $id
+}
+
+pack() {
+	local id="$1"
+	local dir="$TMP/$id"
+	local archive="$dir.tar.gz"
+	tar czf "$archive" -C "$TMP" $id && rm -r "$dir"
+}
+unpack() {
+	local id="$1"
+	local dir="$TMP/$id"
+	local archive="$dir.tar.gz"
+	tar xzf "$archive" -C "$TMP"
+}
+
 unset From To SMTPServer accountname passwd
 
 config() {
 	allcfgconv -C ar7 -c -o - | 
-	sed -ne '/^emailnotify {/,/^}/{/=/{s/ *= */=/;s/^[	]*//;p}}'
+	sed -ne '/^emailnotify {/,/^}/{/=/{s/ *= */=/;s/^[ 	]*//;p}}'
 }
 
+trap 'exit 2' HUP INT QUIT TERM
 case "$1" in
-	enqueue) 
+	send|sendonce|enqueue) 
 		# use push service configuration per default
 		eval "$(config)"
 		FROM="$From"
@@ -57,148 +201,49 @@ case "$1" in
 				--) shift; break ;;
 			esac
 		done
+		id="$(date +%s)-$$"
+		case "$1" in
+			send|enqueue)
+				trap "spool $id" EXIT
+				;;
+			sendonce)
+				trap "remove $id" EXIT
+				;;
+		esac
+		prepare_mail $id
 		;;
 esac
-
-# apply a function to each item in a comma-separated list
-foreach() {
-	local - list="$1" IFS=,
-	alias func="$2"
-	set -f
-	for item in $1; do
-		eval 'func "$item"'
-	done
-	unalias func
-}
-
-# add an item to a comma-separated list
-add() {
-	local name="$1" item="$2"
-	eval "$name=\"\$$name\${$name:+,}\$item\""
-}
-
-# remove all items matching a pattern from the list
-remove() {
-	local name="$1" pattern="$2" TEMP
-	unset TEMP
-	eval "foreach \"\$$name\" remove_func"
-	eval "$name=\$TEMP"
-}
-remove_func() {
-	case "$1" in
-		$pattern) ;;
-		*) add TEMP "$1" ;;
-	esac
-}
-
-escape() {
-	echo "$1" | sed -e "s/'/'\\\\''/g;1s/^/'/;\$s/$/'/"
-}
-
-process_mail() {
-	local id="$1"
-	local archive="$SPOOL/$id.tar.gz"
-	local dir="$TMP/$id"
-	local tmparchive="$dir.tar.gz"
-	ln "$archive" "$TMP"/ && rm "$archive" || return 1
-	tar xzf "$tmparchive" -C "$TMP"
-	(
-		cd "$dir"
-		./send
-		if [ $? -eq 0 ]; then
-			rm "$tmparchive"
-		else
-			ln "$tmparchive" "$SPOOL"/ && rm "$tmparchive"
-		fi
-	)
-	rm -r "$dir"
-}
-
 case "$1" in
+	send)
+		if send $id; then
+			remove $id
+		else
+			spool $id
+		fi
+		;;
+	sendonce)
+		send $id
+		remove $id
+		;;
+	enqueue)
+		spool $id
+		;;
+	process)
+		for mail in "$SPOOL"/*; do
+			id="$(basename "$mail" .tar.gz)"
+			process_mail $id
+		done
+		;;
 	config)
 		config
 		;;
-	send)
-		shift
-		id="$("$0" enqueue "$@")"
-		process_mail "$id"
-		;;
-
-	# should be improved
-	sendonce)
-		shift
-		id="$("$0" enqueue "$@")"
-		process_mail "$id"
-		rm -f "$SPOOL/$id.tar.gz"
-		;;
-	process)
-		shift
-		for mail in "$SPOOL"/*; do
-			id="$(basename "$mail" .tar.gz)"
-			process_mail "$id"
-		done
-		;;
-	enqueue)
-		shift
-		id="$(date +%s)-$$"
-		dir="$TMP/$id"
-		mkdir -p "$dir"
-		COUNT=0
-		save_attachment() {
-			local file="$1" realpath
-			local basename="$(basename "$file")"
-			if [ "$file" = "-" ]; then
-				basename="stdin.txt"
-				realpath="-"
-			else
-				realpath="$(realpath "$file")"
-			fi
-			local subdir="$COUNT"
-			local target="$dir/$subdir/$basename"
-			mkdir "$dir/$subdir"
-			case "$realpath" in
-				/var/*|-) cat "$file" > "$target" ;;
-				*)	ln -s "$realpath" "$target" ;;
-			esac
-			add TEMP "$subdir/$basename"
-			let COUNT="$COUNT + 1"
-		}
-		if [ "${ATTACHMENTS+set}" ]; then
-			unset TEMP
-			foreach "$ATTACHMENTS" save_attachment
-			ATTACHMENTS="$TEMP"
-		fi
-		if [ "${INLINES+set}" ]; then
-			unset TEMP
-			foreach "$INLINES" save_attachment
-			INLINES="$TEMP"
-		fi
-		set -- "$MAILER" "$@" \
-			${SUBJECT+	   "-s" "$SUBJECT"} \
-			${FROM+		   "-f" "$FROM"} \
-			${TO+		   "-t" "$TO"} \
-			${MAILSERVER+  "-m" "$MAILSERVER"} \
-			${AUTHNAME+    "-a" "$AUTHNAME"} \
-			${PASSWORD+    "-w" "$PASSWORD"} \
-			${ATTACHMENTS+ "-d" "$ATTACHMENTS"} \
-			${INLINES+	   "-i" "$INLINES"}
-		script="$dir/send"
-		{
-			printf "#!/bin/sh\n"
-			for arg in "$@"; do
-				printf "%s " "$(escape "$arg")"
-			done
-			printf "\n"
-		} > "$script"
-		chmod +x "$script"
-		archive="$dir.tar.gz"
-		tar czf "$archive" -C "$TMP" "$id" && rm -r "$dir"
-		ln "$archive" "$SPOOL"/ && rm "$archive"
-		echo "$id"
+	list)
+		ls -l "$SPOOL"
 		;;
 	*)
 		usage 1>&2
 		exit 1
 		;;
 esac
+trap "" EXIT
 exit 0
